### ISSUE TITLE
123

### ISSUE THREAD

**Issue by haipengchen01** [739823891/Test#1]

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/44698454-85c54a00-aab2-11e8-9a25-62837745e3ea.png)

**Comment by haipengchen01** [comment]
https://download.opensuse.org/repositories/devel:/CaaSP:/2.0:/ControllerNode/SLE_12_SP3/

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/44780418-7a5a4780-abb4-11e8-8889-81b4b02d0a4a.png)

**Comment by haipengchen01** [comment]
kubectl get secret/promtheus -o jsonpath='{.data.token}' | base64 -D

**Comment by haipengchen01** [comment]
server=https://127.0.0.1:9053
# the name of the secret containing the service account token goes here
name=prometheus-token-4rgms

ca=$(kubectl get secret/$name -o jsonpath='{.data.ca\.crt}')
token=$(kubectl get secret/$name -o jsonpath='{.data.token}' | base64 -D)
namespace=$(kubectl get secret/$name -o jsonpath='{.data.namespace}' | base64 -D)

echo "
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${token}
" > sa.kubeconfig

**Comment by haipengchen01** [comment]
```
echo "
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${token}
" > sa.kubeconfig

```

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45273654-39343280-b4e6-11e8-9d35-be46f0ba2728.png)

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45273831-02125100-b4e7-11e8-9a7d-1861fb6649a9.png)

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45282643-16b60f80-b50e-11e8-8240-f1b0cf025007.png)

**Comment by haipengchen01** [comment]
https://github.com/etcd-io/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45340170-1b3efe80-b5c8-11e8-9bb8-c999c7d4c4ee.png)

**Comment by haipengchen01** [comment]
Refreshing service 'spacewalk'.
Problem retrieving the repository index file for service 'spacewalk':
[spacewalk|file:/usr/lib/zypp/plugins/services/spacewalk] This system is not registered to any spacewalk server. If the system is not intended to be managed with spacewalk, please uninstall the zypp-plugin-spacewalk package.

Warning: Skipping service 'spacewalk' because of the above error.
Loading repository data...
Reading installed packages...
No matching items found.

**Comment by haipengchen01** [comment]
curl registry-1.docker.io
curl: (7) Failed to connect to 53.99.91.27 port 3128: Connection timed out

**Comment by haipengchen01** [comment]
SCDCA0000793:~ # telnet 53.99.33.187 9000
Trying 53.99.33.187...
telnet: connect to address 53.99.33.187: Connection timed out

**Comment by haipengchen01** [comment]
https://download.opensuse.org/update/leap/42.3/oss//

**Comment by haipengchen01** [comment]
https://scan.lbsbackend.mercedes-benz.com.cn/root/kubernetes.git

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45613496-2d71de80-ba99-11e8-94e7-885bc4033be3.png)

**Comment by haipengchen01** [comment]
TCDCA0000657:~ # kubectl logs -f admin-bff-qa-665b98c86c-d5pqd -n qa
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x70df37 m=0

goroutine 0 [idle]:

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x814ba0, 0xc420054058, 0x7e9264, 0xc, 0x17, 0x3)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.goparkunlock(0xc420054058, 0x7e9264, 0xc, 0xbb3517, 0x3)
	/usr/local/go/src/runtime/proc.go:265 +0x5e
runtime.chanrecv(0x7782e0, 0xc420054000, 0x0, 0xc420047f01, 0x42f541)
	/usr/local/go/src/runtime/chan.go:496 +0x2df
runtime.chanrecv1(0x7782e0, 0xc420054000, 0x0)
	/usr/local/go/src/runtime/chan.go:378 +0x35
runtime.gcenable()
	/usr/local/go/src/runtime/mgc.go:196 +0x84
runtime.main()
	/usr/local/go/src/runtime/proc.go:151 +0x12a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

rax    0x0
rbx    0xb9aa08
rcx    0x70df37
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x81dd64
rsp    0x7ffd9722db18
r8     0xa
r9     0x1ce1880
r10    0x8
r11    0x202
r12    0x0
r13    0xf3
r14    0x30
r15    0x3
rip    0x70df37
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
container_linux.go:247: starting container process caused "process_linux.go:270: sending config to init process caused \"write parent: broken pipe\""
TCDCA0000657:~ #

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/45990500-24919600-c0b3-11e8-9694-28d6babaf860.png)

**Comment by haipengchen01** [comment]
cDCgwpHTCN3KyWiL

**Comment by haipengchen01** [comment]
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/46196577-186b3a00-c33a-11e8-9fbb-f54b5a048037.png)

**Comment by haipengchen01** [comment]
./configure --with-pcre=/home/appadmin/pcre-8.42/ --with-openssl=/home/appadmin/openssl-1.0.2p --prefix=/etc --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-pcre-jit

**Comment by haipengchen01** [comment]
docker run -d --name kong     --link kong-database:kong-database     -e "KONG_DATABASE=postgres"     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database"     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout"     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"     -e "KONG_PROXY_ERROR_LOG=/dev/stderr"     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr"     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001"     -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444"  -e "KONG_PG_HOST=kong-database"     -p 9000:8000     -p 9443:8443     -p 9001:8001     -p 9444:8444     kong

**Comment by haipengchen01** [comment]
docker run -d --name kong-database -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" -v /data/kong/:/var/lib/postgresql/data postgres:9.5

**Comment by haipengchen01** [comment]
![image](https://user-images.githubusercontent.com/17328039/47072547-d6dafa00-d228-11e8-9b43-452904469bb5.png)
